CmsBundle\Entity\Accueil:
    type: entity
    table: null
    repositoryClass: CmsBundle\Repository\AccueilRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
            column: Titre
        image:
            type: string
            length: 255
            column: Image
        contenu:
            type: string
            length: 255
            column: Contenu
    lifecycleCallbacks: {  }
