CmsBundle\Entity\Accueil:
    type: entity
    table: null
    repositoryClass: CmsBundle\Repository\AccueilRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
            column: Titre
        premiertitre:
            type: string
            length: 255
            column: premierTitre
        premiercontenu:
            type: string
            length: 255
            column: premierContenu
        deuxiemetitre:
            type: string
            length: 255
            column: deuxiemeTitre
        deuxiemecontenu:
            type: string
            length: 255
            column: deuxiemeContenu
        troisiemetitre:
            type: string
            length: 255
            column: troisiemeTitre
        troisiemecontenu:
            type: string
            length: 255
            column: troisiemeContenu
        image:
            type: string
            length: 255
            nullable: true
            column: Image
        contenu:
            type: string
            length: 255
            column: Contenu
    lifecycleCallbacks:
        prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
        preUpdate: [ preUpload, setUpdatedAtValue ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]

    manyToOne:
        langue:
            targetEntity: CmsBundle\Entity\Langue
