CmsBundle\Entity\Artiste:
    type: entity
    table: null
    repositoryClass: CmsBundle\Repository\ArtisteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            column: Nom
        image:
            type: string
            length: 255
            column: Image
        texte:
            type: string
            length: 255
            column: texte
        lien:
            type: string
            length: 255
            column: lien
        date:
            type: datetime
        ajouterslider:
            type: boolean
        archive:
            type: boolean
        langue:
            type: string
            lenght: 2
        item_id:
            type: integer
            generator:
                strategy: IDENTITY

    lifecycleCallbacks:
          prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
          preUpdate: [ preUpload, setUpdatedAtValue ]
          postPersist: [ upload ]
          postUpdate: [ upload ]
          postRemove: [ removeUpload ]

    oneToMany:
        artiste:
            targetEntity: CmsBundle\Entity\Artiste
            mappedBy: artiste
            cascade:   [persist]

    manyToOne:
        categorie:
            targetEntity: CmsBundle\Entity\Categorie