CmsBundle\Entity\Commercant:
    type: entity
    table: null
    repositoryClass: CmsBundle\Repository\CommercantRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        image:
            type: string
            length: 255
            column: image
        adresse:
            type: string
            length: 255
        code:
            type: integer
        ville:
            type: string
            length: 255
    lifecycleCallbacks: {  }
