CmsBundle\Entity\Commercant:
    type: entity
    table: null
    repositoryClass: CmsBundle\Repository\CommercantRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        adresse:
            type: string
            length: 255
            column: Adresse
        codepostal:
            type: string
            length: 255
            column: Codepostal
        ville:
            type: string
            length: 255
            column: Ville
        pays:
            type: string
            length: 255
            column: Pays
    lifecycleCallbacks: {  }
