CmsBundle\Entity\Presse:
    type: entity
    table: null
    repositoryClass: CmsBundle\Repository\PresseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            column: Nom
        image:
            type: string
            length: 255
            column: image
        texte:
            type: string
            length: 255
            column: texte
        lien:
            type: string
            length: 255
            column: lien
        date:
            type: date
    lifecycleCallbacks:
          prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
          preUpdate: [ preUpload, setUpdatedAtValue ]
          postPersist: [ upload ]
          postUpdate: [ upload ]
          postRemove: [ removeUpload ]

    manyToOne:
        langue:
            targetEntity: CmsBundle\Entity\Langue
