flux_rss:
    resource: "@FluxRSSBundle/Resources/config/routing.yml"
    prefix:   /

cms:
    resource: "@CmsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
