cms_homepage:
    path:     /
    defaults: { _controller: CmsBundle:User:index }

cms_accueil:
    resource: "@CmsBundle/Resources/config/routing/accueil.yml"
    prefix:   /admin/accueil

cms_artiste:
    resource: "@CmsBundle/Resources/config/routing/artiste.yml"
    prefix:   /admin/artiste

cms_commercant:
    resource: "@CmsBundle/Resources/config/routing/commercant.yml"
    prefix:   /admin/commercant

cms_partenaire:
    resource: "@CmsBundle/Resources/config/routing/partenaire.yml"
    prefix:   /admin/partenaire

cms_presse:
    resource: "@CmsBundle/Resources/config/routing/presse.yml"
    prefix:   /admin/presse

user:
    resource: "@CmsBundle/Resources/config/routing/user.yml"
    prefix:   /user


#index:
#    path:     /
#    defaults: { _controller: CmsBundle:Commercant:index }
#
#new:
#    path:     /new
#    defaults: { _controller: CmsBundle:Commercant:new }
#
#show:
#    path:     /show
#    defaults: { _controller: CmsBundle:Commercant:show }
#
#edit:
#    path:     /edit
#    defaults: { _controller: CmsBundle:Commercant:edit }
#
#delete:
#    path:     /delete
#    defaults: { _controller: CmsBundle:Commercant:delete }
