cms_accueil:
    resource: "@CmsBundle/Resources/config/routing/accueil.yml"
    prefix:   /accueil

cms_artiste:
    resource: "@CmsBundle/Resources/config/routing/artiste.yml"
    prefix:   /artiste

cms_commercant:
    resource: "@CmsBundle/Resources/config/routing/commercant.yml"
    prefix:   /commercant

cms_homepage:
    path:     /
    defaults: { _controller: CmsBundle:Default:index }

admin_homepage:
    path:     /admin
    defaults: { _controller: CmsBundle:Admin:index }

user_index:
    path:     /userindex
    defaults: { _controller: CmsBundle:User:index }

user_artiste:
    path:     /userartistes
    defaults: { _controller: CmsBundle:User:artistes }

user_commercant:
    path:     /usercommercants
    defaults: { _controller: CmsBundle:User:commercants }

user_partenaire:
    path:     /userpartenaires
    defaults: { _controller: CmsBundle:User:partenaires }

