Ens\CmsBundle\Entity\Accueil:
    properties:
        # ...
        file:
            - Image: ~


Ens\CmsBundle\Entity\Artiste:
    properties:
        # ...
        file:
            - Image: ~

Ens\CmsBundle\Entity\Partenaire:
    properties:
        # ...
        file:
            - Image: ~