CmsBundle\Entity\Accueil:
    properties:
        # ...
        file:
            - Image: ~

CmsBundle\Entity\Artiste:
    properties:
        # ...
        file:
            - Image: ~

CmsBundle\Entity\Partenaire:
    properties:
        # ...
        file:
            - Image: ~

CmsBundle\Entity\Presse:
    properties:
        # ...
        file:
            - Image: ~