accueil_new:
    path:     /new
    defaults: { _controller: "CmsBundle:Accueil:new" }
    methods:  [GET, POST]

accueil_edit:
    path:     /{id}/edit
    defaults: { _controller: "CmsBundle:Accueil:edit" }
    methods:  [GET, POST]
