newsletter_index:
    path: /
    defaults: { _controller: CmsBundle:AbonnementNewsletters:index }
    methods: GET

newsletters_show:
    path:     /show_newsletters
    defaults: { _controller: CmsBundle:Newsletter:index }
    methods: GET

newsletter_show:
    path:     /newsletter_show/{id}
    defaults: { _controller: CmsBundle:Newsletter:show }
    methods: GET
    requirements:
        id:  \d+

newsletter_create:
    path:     /newsletter_create
    defaults: { _controller: CmsBundle:Newsletter:newsletterCreate }
    methods:  [GET, POST]

newsletter_delete:
    path:     /newsletter_delete/{id}
    defaults: { _controller: CmsBundle:Newsletter:delete }
    methods: [GET, POST]
    requirements:
        id:  \d+

newsletter_edit:
    path:     /newsletter_edit/{id}
    defaults: { _controller: CmsBundle:Newsletter:edit }
    methods: [GET, POST]
    requirements:
        id:  \d+

newsletter_send:
    path:     /newsletter_send/{id}
    defaults: { _controller: CmsBundle:Newsletter:sendMail }
    methods: [GET, POST]
    requirements:
        id:  \d+